"""Asset-class enums shared across trading and market data."""

from __future__ import annotations

from enum import Enum

from market_data.models import AssetType

__all__ = ["AssetType"]


class CryptoOrderSizingMode(str, Enum):
    NOTIONAL = "NOTIONAL"
    QUANTITY = "QUANTITY"


class CryptoTradingStatus(str, Enum):
    NOT_CHECKED = "NOT_CHECKED"
    READY = "READY"
    ACCOUNT_NOT_ELIGIBLE = "ACCOUNT_NOT_ELIGIBLE"
    ASSET_NOT_TRADABLE = "ASSET_NOT_TRADABLE"
    CONFIGURATION_DISABLED = "CONFIGURATION_DISABLED"
    KILL_SWITCH_ENGAGED = "KILL_SWITCH_ENGAGED"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"


class CryptoLedgerEntryType(str, Enum):
    CRYPTO_ALLOCATION = "CRYPTO_ALLOCATION"
    CRYPTO_ALLOCATION_INCREASE = "CRYPTO_ALLOCATION_INCREASE"
    CRYPTO_ALLOCATION_DECREASE = "CRYPTO_ALLOCATION_DECREASE"
    CRYPTO_BUY_RESERVE = "CRYPTO_BUY_RESERVE"
    CRYPTO_BUY_RESERVE_RELEASE = "CRYPTO_BUY_RESERVE_RELEASE"
    CRYPTO_BUY_USD_DEBIT = "CRYPTO_BUY_USD_DEBIT"
    CRYPTO_BUY_ASSET_CREDIT = "CRYPTO_BUY_ASSET_CREDIT"
    CRYPTO_SELL_ASSET_DEBIT = "CRYPTO_SELL_ASSET_DEBIT"
    CRYPTO_SELL_USD_CREDIT = "CRYPTO_SELL_USD_CREDIT"
    CRYPTO_FEE_USD_DEBIT = "CRYPTO_FEE_USD_DEBIT"
    CRYPTO_FEE_ASSET_DEBIT = "CRYPTO_FEE_ASSET_DEBIT"
    CRYPTO_ADJUSTMENT = "CRYPTO_ADJUSTMENT"


class CryptoFeeStatus(str, Enum):
    ESTIMATED = "ESTIMATED"
    CONFIRMED = "CONFIRMED"
    NOT_AVAILABLE = "NOT_AVAILABLE"
